@host = https://localhost
@port = 7272
@KasiCornerKota_API_HostAddress = https://localhost:7272
@token = CfDJ8ODwGfDpVsZFrPxfC2bFSY3Y3d9XKkGz_Uj6h9cY8-2Zk5Zm5NMcYiOpgLRsLiiPXYJZXAPogfKACFjhsjSSo6KiDS4g1iow7JzSa8jnv9oz-WR4OcAkHWlboN1SwABxAv9Tq2YhCJqLDfzpw-ZYpHb5XkXA-xFNuNRwZ7oJaWFuBJJPY5W_-RfZ-10Lo8Y_aRJX1RCpW-Xk29LmxhE_6zFKqqd9YRjHW8EQr2xeajfIorQjOcV1E_VcycFVLALgYr8O55kIz2xzV_ALlVdTPOnK2IdE1Iy6y1i3rZUXs9loUNIbtS9vVE62ge-6pwqL4nqzbQiwfqtC7bOjJUvdwPZp4aYEgdvGmk5CeLDMAzF3jTq4PdHs8b_9Od5GuR9H9B50-6p41btfHmLq2C9IU71SPS42LWMT1G3xLaYZ6u7TYEFKlHV9c8C1xuUO3uyesdIySov3aS3ZMPx9bjBNrjtoqcLiCrEmB4p5my99i5Y52AGLf-QcnZ5GpjuWHGLeqSxA-xjhkoBivZymC_Zt9UOruneY_WghY9deKQJYUDPGCr3ODZA7X9HGfjR3p58Ey6xF2v2j-1SQnKuQKpJWy-m95o6tbR_YZG5sUGsG-JvTb4kweSiNjDFmnRCH4N97lGBfTMW-8z9sWmXlNqNUn24LKjAg1sElESNaN4zzccPpakQd--fiH13jGNboKf4ZpJq-ryxq4Ew9Jt7GRwtQcw4Rj5iUWHJF3Kf7RMbLsclE-woLhVXF5knM3Lg86jqNzrdNE6oLlofAc1OZGWR27cvsMVDDpaOoOaK5qdETcona

GET {{KasiCornerKota_API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=10&pageCount=2&sortBy=Name&sortDirection=Descending
Authorization : Bearer {{token}}
###


GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/9994024
Authorization : Bearer {{token}}

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "Name":"Owner Test2 Shisa2",
  "Description": "Phuthu, Wors, Liver & Beef",
  "Category": "Fast Food",
  "HasDelivery" : true,
  "ContactEmail" : "kornerkota@kasi.co.za",
  "PhoneNumber": "078-525-3201",
  "City" : "Tembisa",
  "Street" : "84 Enhlanzeni Hostel",
  "PostalCode" : "1632"
}

###

PATCH {{KasiCornerKota_API_HostAddress}}/api/restaurants/1003
Content-Type: application/json
Authorization : Bearer {{token}}

{
 "Name":"Onwer Updated Special",
"Description": "Chips, Polony, Atchar, eggs, Russian & Vianna",
"HasDelivery" : false
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants/8/dishes
Content-Type: application/json

{
  "Name": "Kota, Chips and Special",
  "Description": "Fast food yase Kasi",
  "Price": 12.99,
  "Calories": 50
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "P@55word1"
}

###

  
POST {{KasiCornerKota_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
   "email": "Owner2@test.com",
  "password": "P@55word1"
}

###

PATCH {{KasiCornerKota_API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "dateOfBirth": "2013-05-04",
  "Nationality": "Botswana"
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "UserEmail" : "Owner2@test.com",
  "RoleName" : "Owner"
}

###

@restaurantId=8
GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Authorization : Bearer {{token}}

###

@id=9994024
DELETE {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{id}}
Authorization : Bearer {{token}}
###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants/{id}/logo
Authorization : Bearer {{token}}
Content-Type: application/json

{
  "C:\Users\User\Downloads\shisa-nyama-Logo.jpg"
}

###
