@host = https://localhost
@port = 7272
@KasiCornerKota_API_HostAddress = https://localhost:7272

###

###

GET {{KasiCornerKota_API_HostAddress}}/api/restaurants

###

@id=2
GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{id}}

###
