@host = https://localhost
@port = 7272
@KasiCornerKota_API_HostAddress = https://localhost:7272
@token = CfDJ8ODwGfDpVsZFrPxfC2bFSY2nRqFHp3m85pktrylgG53B1Pu9xv2dWYicTIocR20LA2RFyLQXMA7tNw3BQfGMb0729metNhCQ8PPa9yudv36RKfF4Igdo91Ucpv8d8slX2Ha3gCg3GaYcgDS8D5T2outLZDYa6AJbHRNQ04guzF2OcO3Y_BMGtvQWLKSIdbWNDgd5vTVcb3ph0Vkvo2JLhjI901Vr1559CPePKKXYZZwiXVSkWfJ3FrUx1jjvA8is8H7gReuFaXOkJ9ZOyg83x41-Syd9CJpVrocyLuN-qwxo0vtu9et1B0C6r13KnIkcbnetqcHMbE5iv1mjlAK89uXzvbS7rJ5dlN9Iv-Soewkdo4qPTnoX8f5y3Nyu_t15Xi1rc4FP1wkhghqURGcjWUGxirgapmb9vUFqp-RIEYBsWYvyw1WboxIuaSn-Ej_ajcwRjwC94aDAmFkH2y6depVo9MckjsW376POfK9OcmfE4eJKUg-SE2f1NvQteV16giGMvyeuIJqeyaT_VH8hfPuNCRtaSCtnzI65xI05p-zOeuA2iN0TqDNsztsyV4WXoSb6_eu_UvrmtpAVdr20TslU7YC0lLcA-_pRdetvci8O8wVqXRmUvMPSZ9QBQblEybx5E2qwST3d4RNu2u3f2tmwn7mZZuCm5b7FC77ACxrYn7xibE0c7R3YYopfCEOP2r2Y-9wFfCJuOQtq6r3NMNMadzUIRcmfwsVDDIQUibkHR5j6VCKws3c1M4Cs7u0k41sIjB3VI9Y8xd0GfzKXsnxvkmppD3sfWInAodHdlNHX

GET {{KasiCornerKota_API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=10&pageCount=2&sortBy=Name&sortDirection=Descending
Authorization : Bearer {{token}}
###


GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/10
Authorization : Bearer {{token}}

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "Name":"Owner Test2 Shisa2",
  "Description": "Phuthu, Wors, Liver & Beef",
  "Category": "Fast Food",
  "HasDelivery" : true,
  "ContactEmail" : "kornerkota@kasi.co.za",
  "PhoneNumber": "078-525-3201",
  "City" : "Tembisa",
  "Street" : "84 Enhlanzeni Hostel",
  "PostalCode" : "1632"
}

###

PATCH {{KasiCornerKota_API_HostAddress}}/api/restaurants/1003
Content-Type: application/json
Authorization : Bearer {{token}}

{
 "Name":"Onwer Updated Special",
"Description": "Chips, Polony, Atchar, eggs, Russian & Vianna",
"HasDelivery" : false
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants/8/dishes
Content-Type: application/json

{
  "Name": "Kota, Chips and Special",
  "Description": "Fast food yase Kasi",
  "Price": 12.99,
  "Calories": 50
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "P@55word1"
}

###

  
POST {{KasiCornerKota_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "Owner2@test.com",
  "password": "P@55word1"
}

###

PATCH {{KasiCornerKota_API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "dateOfBirth": "2013-05-04",
  "Nationality": "Botswana"
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization : Bearer {{token}}

{
  "UserEmail" : "Owner2@test.com",
  "RoleName" : "Owner"
}

###

@restaurantId=8
GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Authorization : Bearer {{token}}

###

@id=10
DELETE {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{id}}
Authorization : Bearer {{token}}
###
