@host = https://localhost
@port = 7272
@KasiCornerKota_API_HostAddress = https://localhost:7272

###

###

GET {{KasiCornerKota_API_HostAddress}}/api/restaurants

###


GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/8

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name":"Shisanyama Busy Corner",
  "Description": "Phuthu, Wors, Liver & Beef",
  "Category": "Fast Food",
  "HasDelivery" : true,
  "ContactEmail" : "kornerkota@kasi.co.za",
  "PhoneNumber": "078-525-3201",
  "City" : "Tembisa",
  "Street" : "84 Enhlanzeni Hostel",
  "PostalCode" : "1632"
}

###
@id=7
DELETE {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{KasiCornerKota_API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
 "Name":"Kota Weekend Special",
"Description": "Chips, Polony, Atchar, eggs, Russian & Vianna",
"HasDelivery" : false
}

###

POST {{KasiCornerKota_API_HostAddress}}/api/restaurants/8/dishes
Content-Type: application/json

{
  "Name": "Kota, Chips and Special",
  "Description": "Fast food yase Kasi",
  "Price": 12.99,
  "Calories": 50
}

###

@restaurantId=8
@dishId=6
GET {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

@restaurantId=8
DELETE {{KasiCornerKota_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
